# Generated by Django 5.0.1 on 2024-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('Reading', 'reading'), ('Finished', 'fimished')], default='New', max_length=10),
        ),
    ]
